---
title: "Quiz 2"
author: "Andrew McLain"
date: "`r Sys.Date()`"
output: openintro::lab_report
---

```{r load-packages, message=FALSE, warning=FALSE}
library(openintro)
#if (!require(tidyverse)) install.packages('tidyverse')
library(tidyverse)
#if (!require(readxl)) install.packages('readxl')
library(readxl)
library(mdsr)
library(readr)
library(dplyr)
library(nycflights13)
install.packages("zoo", repos =
                   "http://cran.us.r-project.org")
```

### Exercise 1

```{r exercise 1a, message=FALSE, warning=FALSE}
revenue <- read_csv("https://bit.ly/385faPm")
revenue1 <- revenue %>%
            pivot_longer(cols = Qtr_1:Qtr_4,
                         names_to = "Quarter",
                         values_to = "Revenue")
revenue1
```

```{r exercise 1b, message=FALSE, warning=FALSE}
revenue1a <- revenue1 %>%
           group_by(Group, Year) %>%
           summarize(annualRevenue = sum(Revenue)) %>%
           arrange(Year, desc(annualRevenue))
revenue1a

```
```{r exercise 1c, message=FALSE, warning=FALSE}
revenue2 <- revenue %>%
            rename("1" = Qtr_1,
                   "2" = Qtr_2,
                   "3" = Qtr_3,
                   "4" = Qtr_4) %>%
            pivot_longer(cols = "1":"4",
                         names_to = "Quarter",
                         values_to = "Revenue") %>%
            arrange(Quarter, Group) %>%
  unite("Year_Quarter", c("Year", "Quarter"), sep="-")


            
revenue2

```

```{r exercise_1d, message=FALSE, warning=FALSE}
library(zoo)
revenue2 <- mutate(revenue2, Year_Quarter =
                     as.yearqtr(Year_Quarter))

ggplot(data = revenue2, 
       mapping = aes(x=Year_Quarter,
                     y=Revenue)) + 
       geom_line(mapping = aes(color = Group)) + 
       scale_x_yearqtr(format = "%Y-Q%q") +
       xlab("Year-Quarter") +
       ylab("Revenue (millions of $)")
```

### Exercise 2

```{r exercise 2a, message=FALSE, warning=FALSE}
NYCdestinations <- flights %>%
                   group_by(dest) %>%
                   summarize(totalFlights = n(),
                             mean_arr_delay =
                               mean(arr_delay, 
                                    na.rm=TRUE),
                             mean_distance =
                               mean(distance,
                                    na.rm=TRUE))
NYCdestinations
```

```{r exercise 2b, message=FALSE, warning=FALSE}
NYCdestinations %>%
  left_join(airports, by = c("dest" = "faa")) %>%
  filter(totalFlights >= 365) %>%
  arrange(desc(mean_arr_delay)) %>%
  select("name", "mean_arr_delay", "mean_distance") %>%
  head(5)

```

```{r exercise 2c, message=FALSE, warning=FALSE}
NYCdestinations2 <- NYCdestinations  %>%
  left_join(airports, by = c("dest" = "faa")) %>%
  filter(totalFlights >= 365) %>%
  arrange(desc(mean_arr_delay))

ggplot(NYCdestinations2, mapping = 
         aes(x = mean_distance,
             y = mean_arr_delay,
             size = totalFlights)) +
         geom_point(alpha = 1/3) +
         geom_smooth(se=FALSE)
```

```{r exercise 2d, message=FALSE, warning=FALSE}
NYCdestinations2 <- NYCdestinations2  %>%
  filter(totalFlights >= 365,
         mean_distance <= 4500)

ggplot(NYCdestinations2, mapping = 
         aes(x = mean_distance,
             y = mean_arr_delay,
             size = totalFlights)) +
         geom_point(alpha = 1/3) +
         geom_smooth(se=FALSE)
```
```{r exercise 2e, message=FALSE, warning=FALSE}

```
The longer flights tend to have shorter average delay times. I believe this is because as the flights get longer, the time for take off and landing make up a smaller percentage of the total flight time. Therefore, the plane can make up for lost time by flying faster for longer flights, but this is more difficult for shorter flights.  
